### ISSUE TITLE
please submit to the GNU ELPA

### ISSUE THREAD

**Issue by tzz** [jwiegley/emacs-pl#1]
Great library, I've been waiting for something like this!

I'd love to have this in Emacs by default.  Can you please submit it to the GNU ELPA?  I can do it if you wish.

**Comment by jwiegley** [comment]
I'm more than happy to have in ELPA, and all my papers are signed, we just need to modify the copyright notice to assign rights to the FSF.

Note that there are still some functions to be written, like `pl-many` for repeating a parser until it fails, and collecting all the results together as a list.  But the core shouldn't be far from completion, since the whole point is to leverage ordinary Lisp forms as a way of constructing complex parsers.

**Comment by jwiegley** [comment]
Also, if you want the expedite things, you have my go ahead to make the necessary changes and submit to ELPA. :)

**Comment by jwiegley** [comment]
@tzz How would you like to just become maintainer for emacs-pl?

**Comment by tzz** [comment]
Sorry for the delay @jwiegley 

I can take over as maintainer, sure.  As far as the Github repos, we'd need to switch to my copy or you can give me commit access to yours.  Up to you.

We could even ask to put this in the core Emacs repo, since it's a pretty basic module (and thus can be considered on the level of Semantic, etc. but much easier to use).  Do you care if I propose that on emacs-devel?  It will definitely require your copyright assignment but I thought that was already on file.  Well, let me know.

Regarding `pl-many`: put your ideas in a TODO file and then we can work on them as time allows.  I don't know your original plan for this and I don't know the Haskell source of inspiration, so I need your wise guidance :)

**Comment by jwiegley** [comment]
@tzz I've given you commit rights.  If this can take off in your hands, I'll transfer ownership at a later date.

I did write `pl-many`.  There shouldn't be too many other combinators needed.

I'd be happy for this to go into core Emacs, propose away!

**Comment by tzz** [comment]
Resolved by inclusion in core Emacs!

**Comment by jwiegley** [comment]
Haha.  @tzz I think that at first we will put it in ELPA, with the intention being that it goes into the "tarball subset of ELPA". I'd like to do that until the ELPA Policy is agreed on, at which time we'll then review everything in and out of ELPA, and decide what should go where.
